#File 경로 @Value("${file.dir") 로 값을 불러올 수 있음.
file:
  dir: C:\Users\0628c\OneDrive\바탕 화면\toyP\toyproject\src\main\resources\static\image\

#ErrorMessage 연결
spring:
  
  #파일 업로드 관련
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  
  #message 설정
  messages:
    basename: errors

  #liveReLoad
  devtools:
    livereload:
      enabled: true

  #H2 DB 설정
    profiles: H2
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa

#SessionTrackingMode Off
server:
  servlet:
    session:
      tracking-modes: cookie


#MyBatis
mybatis:
  type-aliases-package: syh.toyProject.domain

  configuration:
    map-underscore-to-camel-case: true

  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    syh:
      toyProject:
        repository:
          mybatis: trace

