create table member
(
   member_id bigint generated by default as identity,
   signup_date datetime,
   login_id varchar(20),
   password varchar(20),
   username varchar(20),
   primary key (member_id)
);

create table post
(
   post_id bigint generated by default as identity,
   member_id bigint,
   writing_date datetime,
   last_edit_date datetime,
   view_count bigint,
   post_title varchar(50),
   post_content varchar(100)
   primary key (post_id)
);

create table comment
(
   comment_id bigint generated by default as identity,
   member_id bigint,
   post_id bigint,
   writing_date datetime,
   last_edit_date datetime,
   comment_content varchar(100),
   primary key (comment_id)
);

create table post_recommend
(
    post_id bigint,
    recommender_id bigint,
    recommend_date datetime
);

create table image
(
    image_id bigint generated by default as identity,
    post_id bigint,
    origin_name varchar(255),
    server_name varchar(50),
    file_size bigint,
    upload_date datetime,
    primary key (image_id)
)